name: Generate Signing Key

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore my-tuition-manager.jks \
            -alias mytuition \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass MyTuitionKey2026 \
            -keypass MyTuitionKey2026 \
            -dname "CN=The Math Guild, OU=My Tuition Manager, O=The Math Guild, L=India, ST=West Bengal, C=IN"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: my-tuition-manager-keystore
          path: my-tuition-manager.jks
      - name: Create Base64 keystore
        run: |
          base64 -w 0 my-tuition-manager.jks > my-tuition-manager.txt

      - name: Upload Base64 keystore
        uses: actions/upload-artifact@v4
        with:
          name: my-tuition-manager-base64
          path: my-tuition-manager.txt
